# Generated by Django 2.0.7 on 2020-08-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('altbaslik', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('icerik', models.CharField(max_length=200)),
                ('resim', models.FileField(null=True, upload_to='documents/')),
            ],
        ),
    ]
