# Generated by Django 2.0.7 on 2020-08-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='welcome',
        ),
    ]
