# Generated by Django 2.0.7 on 2020-08-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0002_delete_welcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('icerik', models.CharField(max_length=200)),
            ],
        ),
    ]
