# Generated by Django 2.0.7 on 2020-08-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=50)),
                ('altbaslik', models.CharField(max_length=200)),
                ('yazan', models.CharField(max_length=200)),
            ],
        ),
    ]
