# Generated by Django 2.0.7 on 2020-08-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0005_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallery',
            new_name='galery',
        ),
    ]
